#!/usr/bin/env python3
"""Select a build profile in a checkout before the TinyTapeout GDS action."""
import argparse
from pathlib import Path
import re
from configurations import CONFIGS, validate

TILES = dict(tiny='1x1', small='1x2', default='2x2', wide_acc='2x2', rectangular='3x2')
ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('name', choices=list(TILES))
    args = parser.parse_args()
    config = CONFIGS[args.name]
    validate(config)
    header = ['// SPDX-License-Identifier: Apache-2.0', '// Synthesis defaults; generated by scripts/select_config.py.']
    for key, value in config.items():
        header += [f'`ifndef MAC_{key}', f'`define MAC_{key} {value}', '`endif']
    (ROOT / 'src/config.vh').write_text('\n'.join(header)+'\n')
    path = ROOT / 'info.yaml'
    path.write_text(re.sub(r'tiles: "[^"]+"', f'tiles: "{TILES[args.name]}"', path.read_text()))
    print(f'Selected {args.name}: {config}, tiles={TILES[args.name]}')


if __name__ == '__main__':
    main()
