// SPDX-License-Identifier: Apache-2.0
// Synthesis defaults; generated by scripts/select_config.py.
`ifndef MAC_DATA_W
`define MAC_DATA_W 8
`endif
`ifndef MAC_ACC_W
`define MAC_ACC_W 24
`endif
`ifndef MAC_ROWS
`define MAC_ROWS 2
`endif
`ifndef MAC_COLS
`define MAC_COLS 2
`endif
`ifndef MAC_K
`define MAC_K 2
`endif
